%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

%global __cmake_in_source_build 1

Name:           ros-jazzy-fusioncore-ros
Version:        0.2.1
Release:        3%{?dist}%{?release_suffix}
Summary:        ROS fusioncore_ros package

License:        Apache-2.0
URL:            https://index.ros.org/p/fusioncore_ros/#jazzy
Source0:        %{name}-%{version}.tar.gz

Requires:       proj-devel
Requires:       ros-jazzy-compass-msgs
Requires:       ros-jazzy-diagnostic-msgs
Requires:       ros-jazzy-eigen3-cmake-module
Requires:       ros-jazzy-fusioncore-core
Requires:       ros-jazzy-geographic-msgs
Requires:       ros-jazzy-geometry-msgs
Requires:       ros-jazzy-nav-msgs
Requires:       ros-jazzy-rclcpp
Requires:       ros-jazzy-rclcpp-lifecycle
Requires:       ros-jazzy-rosidl-default-runtime
Requires:       ros-jazzy-sensor-msgs
Requires:       ros-jazzy-std-srvs
Requires:       ros-jazzy-tf2
Requires:       ros-jazzy-tf2-geometry-msgs
Requires:       ros-jazzy-tf2-ros
Requires:       ros-jazzy-ros-workspace
BuildRequires:  proj-devel
BuildRequires:  ros-jazzy-ament-cmake
BuildRequires:  ros-jazzy-compass-msgs
BuildRequires:  ros-jazzy-diagnostic-msgs
BuildRequires:  ros-jazzy-eigen3-cmake-module
BuildRequires:  ros-jazzy-fusioncore-core
BuildRequires:  ros-jazzy-geographic-msgs
BuildRequires:  ros-jazzy-geometry-msgs
BuildRequires:  ros-jazzy-nav-msgs
BuildRequires:  ros-jazzy-rclcpp
BuildRequires:  ros-jazzy-rclcpp-lifecycle
BuildRequires:  ros-jazzy-rosidl-default-generators
BuildRequires:  ros-jazzy-rosidl-default-runtime
BuildRequires:  ros-jazzy-sensor-msgs
BuildRequires:  ros-jazzy-std-srvs
BuildRequires:  ros-jazzy-tf2
BuildRequires:  ros-jazzy-tf2-geometry-msgs
BuildRequires:  ros-jazzy-tf2-ros
BuildRequires:  ros-jazzy-ros-workspace
BuildRequires:  ros-jazzy-rosidl-typesupport-fastrtps-c
BuildRequires:  ros-jazzy-rosidl-typesupport-fastrtps-cpp
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}
Provides:       ros-jazzy-rosidl-interface-packages(member)

%if 0%{?with_weak_deps}
Supplements:    ros-jazzy-rosidl-interface-packages(all)
%endif

%description
ROS 2 UKF sensor fusion for GPS, IMU and wheel encoders. 22-state filter with
ECEF-native GPS handling, automatic IMU bias estimation, adaptive noise
covariance, and chi-squared outlier rejection on every sensor. Drop-in
robot_localization alternative. Native ROS 2 Jazzy, benchmarked on 6 NCLT public
dataset sequences.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DAMENT_PREFIX_PATH="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Thu Apr 30 2026 FusionCore <kharwarm@mcmaster.ca> - 0.2.1-3
- Autogenerated by Bloom

* Wed Apr 29 2026 FusionCore <kharwarm@mcmaster.ca> - 0.2.1-2
- Autogenerated by Bloom

* Tue Apr 28 2026 FusionCore <kharwarm@mcmaster.ca> - 0.2.1-1
- Autogenerated by Bloom

* Wed Apr 22 2026 FusionCore <kharwarm@mcmaster.ca> - 0.2.0-1
- Autogenerated by Bloom

* Wed Apr 01 2026 FusionCore <kharwarm@mcmaster.ca> - 0.1.1-1
- Autogenerated by Bloom

* Sat Mar 28 2026 FusionCore <kharwarm@mcmaster.ca> - 0.1.0-1
- Autogenerated by Bloom

